entity_config:
    entity:
        field:
            items:
                is_total:
                    options:
                        require_schema_update: false
                        value_type: boolean
                        default_value: false
                is_total_currency:
                    options:
                        require_schema_update: false
                        value_type: boolean
                        default_value: false
    sharding:
        # You can find out more about attributes in the documentation: https://doc.oroinc.com/backend/configuration/annotation/config.html#sharding
        field:
            items:
                discrimination_field:
                    options:
                        default_value: false
