Oro\Bundle\ProductBundle\Entity\Product:
    fields:
        -
            name: minimal_price_CPL_ID_CURRENCY_UNIT
            type: decimal
            group: pricing
        -
            name: minimal_price_CPL_ID_CURRENCY
            type: decimal
            group: pricing

        -   name: minimal_price_PRICE_LIST_ID_CURRENCY_UNIT
            type: decimal
            group: pricing

        -   name: minimal_price_PRICE_LIST_ID_CURRENCY
            type: decimal
            group: pricing
