layout:
    actions:
        - '@setBlockTheme':
            themes: 'product_kit_shopping_lists.html.twig'
        - '@addTree':
            items:
                __wrapper:
                    blockType: container
                    options:
                        vars:
                            productShoppingLists: '=data.offsetExists("product") ? data["oro_shopping_list_product_units_quantity"].getByProduct(data["oro_product_variant"].getProductVariantOrProduct(data)) : []'
                            product: '=data.offsetExists("product") ? data["oro_product_variant"].getProductVariantOrProduct(data)'
                __button:
                    blockType: block
            tree:
                __root:
                    __wrapper:
                        __button: ~
