api:
    entity_aliases:
        Oro\Bundle\WebsiteSearchBundle\SearchResult\Entity\SearchResultHistory:
            alias: searchresulthistory
            plural_alias: searchresulthistories
    entities:
        Oro\Bundle\WebsiteSearchBundle\SearchResult\Entity\SearchResultHistory:
            documentation_resource: '@OroWebsiteSearchBundle/Resources/doc/api/search_results_history.md'
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
