datagrids:
    oro-website-search-result-history-grid:
        extended_entity_name: Oro\Bundle\WebsiteSearchBundle\SearchResult\Entity\SearchResultHistory
        acl_resource: oro_website_search_result_history_view
        options:
            entityHint: oro.websitesearch.searchresult.entity.searchresulthistory.entity_plural_label
        properties:
            id: ~
        source:
            type: orm
            query:
                select:
                    - e.id
                    - e.searchTerm
                    - e.resultType
                    - e.resultsCount
                    - e.createdAt
                    - website.name as websiteName
                    - localization.name as localizationName
                    - customer.name as customerName
                    - 'TRIM(CONCAT(COALESCE(CONCAT(CAST(customerUser.namePrefix as string), '' ''), ''''), COALESCE(CONCAT(CAST(customerUser.firstName as string), '' ''), ''''), COALESCE(CONCAT(CAST(customerUser.middleName as string), '' ''), ''''), COALESCE(CONCAT(CAST(customerUser.lastName as string), '' ''), ''''), COALESCE(CAST(customerUser.nameSuffix as string), ''''))) as customerUserTitle'
                    - IDENTITY(e.customerVisitor) as customerVisitorId
                from:
                    - { table: 'Oro\Bundle\WebsiteSearchBundle\SearchResult\Entity\SearchResultHistory', alias: e }
                join:
                    left:
                        - { join: e.website, alias: website }
                        - { join: e.localization, alias: localization }
                        - { join: e.customer, alias: customer }
                        - { join: e.customerUser, alias: customerUser }
        columns:
            searchTerm:
                label: oro.websitesearch.searchresult.entity.searchresulthistory.search_term.label
            resultType:
                label: oro.websitesearch.searchresult.entity.searchresulthistory.result_type.label
            resultsCount:
                label: oro.websitesearch.searchresult.entity.searchresulthistory.results_count.label
            createdAt:
                label: oro.websitesearch.searchresult.entity.searchresulthistory.created_at.label
                frontend_type: datetime
            websiteName:
                label: oro.websitesearch.searchresult.entity.searchresulthistory.website.label
            localizationName:
                label: oro.websitesearch.searchresult.entity.searchresulthistory.localization.label
            customerName:
                label: oro.websitesearch.searchresult.entity.searchresulthistory.customer.label
            customerUserTitle:
                label: oro.websitesearch.searchresult.entity.searchresulthistory.customer_user.label
            customerVisitorId:
                label: oro.websitesearch.searchresult.entity.searchresulthistory.customer_visitor_id.label
        sorters:
            columns:
                resultType:
                    data_name: e.resultType
                resultsCount:
                    data_name: e.resultsCount
                websiteName:
                    data_name: websiteName
                localizationName:
                    data_name: localizationName
                customerName:
                    data_name: customerName
                customerUserTitle:
                    data_name: customerUserTitle
                customerVisitorId:
                    data_name: customerVisitorId
                searchTerm:
                    data_name: e.searchTerm
                createdAt:
                    data_name: e.createdAt
            default:
                createdAt: DESC
        filters:
            columns:
                searchTerm:
                    data_name: e.searchTerm
                    type: string
                    case_insensitive: false
                    value_conversion: mb_strtoupper
                resultType:
                    data_name: e.resultType
                    type: string
                    case_insensitive: false
                    value_conversion: mb_strtoupper
                createdAt:
                    data_name: e.createdAt
                    type: datetime
                resultsCount:
                    data_name: e.resultsCount
                    type: number-range
                localizationName:
                    type: string
                    data_name: localization.name
                websiteName:
                    type: string
                    data_name: website.name
                customerName:
                    type: string
                    data_name: customer.name
                customerVisitorId:
                    type: number
                    data_name: customerVisitorId
                customerUserTitle:
                    type: string
                    data_name: customerUserTitle

    website-search-results-report:
        entity_name: 'Oro\Bundle\WebsiteSearchBundle\Entity\SearchTermReport'
        acl_resource: oro_website_search_result_history_view
        options:
            entityHint: oro.websitesearch.searchresult.entity.searchtermreport.entity_plural_label
            export: true
        source:
            type: orm
            query:
                select:
                    - e.searchTerm
                    - e.timesSearched
                    - e.timesReturnedResults
                    - e.timesEmpty
                    - e.searchDate
                from:
                    - { table: 'Oro\Bundle\ReportBundle\Entity\CalendarDate', alias: calendarDate }
                join:
                    inner:
                        - table: Oro\Bundle\WebsiteSearchBundle\Entity\SearchTermReport
                          alias: e
                          conditionType: WITH
                          condition: e.searchDate = CAST(calendarDate.date as DATE)
        columns:
            timePeriod:
                label: oro.report.datagrid.column.time_period.label

            searchTerm:
                label: oro.websitesearch.searchresult.entity.searchtermreport.search_term.label
                cellClassName: 'direction-ltr'
            timesSearched:
                label: oro.websitesearch.searchresult.entity.searchtermreport.times_searched.label
                frontend_type: integer
            timesReturnedResults:
                label: oro.websitesearch.searchresult.entity.searchtermreport.times_returned_results.label
                frontend_type: integer
            timesEmpty:
                label: oro.websitesearch.searchresult.entity.searchtermreport.times_empty.label
                frontend_type: integer
        sorters:
            columns:
                timePeriod:
                    data_name: timePeriod
                    apply_callback: ['@oro_filter.date_grouping_filter', 'applyOrderBy']
                searchTerm:
                    data_name: e.searchTerm
                timesSearched:
                    data_name: e.timesSearched
                timesReturnedResults:
                    data_name: e.timesReturnedResults
                timesEmpty:
                    data_name: e.timesEmpty
            default:
                timePeriod: DESC
        filters:
            columns:
                timePeriod:
                    label: oro.report.datagrid.column.time_period.label
                    type: datetime
                    data_name: searchResult.createdAt
                searchTerm:
                    data_name: e.searchTerm
                    type: string
                timesSearched:
                    data_name: e.timesSearched
                    type: number-range
                timesReturnedResults:
                    data_name: e.timesReturnedResults
                    type: number-range
                timesEmpty:
                    data_name: e.timesEmpty
                    type: number-range
                skip_empty_periods:
                    label: oro.report.filter.skip_empty_periods.label
                    type: skip_empty_periods
                    data_name: searchTerm
                    options:
                        field_options:
                            choices:
                                No: 0
                                Yes: 1
                        default_value: Yes
                grouping:
                    label: oro.report.filter.grouping.label
                    type: date_grouping
                    data_name: calendarDate.date
                    column_name: timePeriod
                    calendar_entity: 'Oro\Bundle\ReportBundle\Entity\CalendarDate'
                    target_entity: 'Oro\Bundle\WebsiteSearchBundle\SearchResult\Entity\SearchResultHistory'
                    not_nullable_field: searchResult.id
                    joined_column: createdAt
                    joined_table: joinedTableAlias
                    options:
                        field_options:
                            choices:
                                Day: day
                                Month: month
                                Quarter: quarter
                                Year: year
                        default_value: Day
            default:
                grouping:
                    value: day
                skip_empty_periods:
                    value: 1
