entity_config:
    attribute:
        # You can find out more about attributes in the documentation: https://doc.oroinc.com/backend/configuration/annotation/config-field.html#attribute
        field:
            items:
                search_boost:
                    options:
                        value_type: 'decimal'
                    form:
                        type: 'Symfony\Component\Form\Extension\Core\Type\NumberType'
                        options:
                            block: 'attribute'
                            required: false
                            label: 'oro.website_search.entity_config.search_boost.label'
                            tooltip: 'oro.website_search.entity_config.search_boost.tooltip'
                            constraints:
                                - Range:
                                    min: 0
                                - Oro\Bundle\ValidationBundle\Validator\Constraints\Decimal: ~
