navigation:
    menu_config:
        items:
            oro_website_search_search:
                label: 'oro.website_search.search.label'
                uri: '#'
                position: 200
            oro_website_search_history:
                label: 'oro.website_search.search_history.label'
                route: 'oro_website_search_search_history'
                extras:
                    routes: ['oro_website_search_search_*']

        tree:
            application_menu:
                children:
                    marketing_tab:
                        children:
                            oro_website_search_search:
                                children:
                                    oro_website_search_history: ~
