services:
    _defaults:
        public: true

    Oro\Bundle\FrontendLocalizationBundle\Controller\Frontend\AjaxLocalizationController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_locale.manager.localization }
            - { name: container.service_subscriber, id: oro_frontend_localization.manager.user_localization }
            - { name: container.service_subscriber, id: oro_locale.helper.localized_slug_redirect }
