services:
    _defaults:
        public: false

    Oro\Bundle\ProductBundle\Command\ProductCollectionsIndexCronCommand:
        arguments:
            - '@oro_message_queue.client.message_producer'
            - '@oro_product.model.segment_message_factory'
            - '@oro_product.provider.segment_with_relations_provider'
            - '@oro_product.helper.product_collection_segment'
            - '@oro_config.manager'
        calls:
            - ['setReindexHandler', ['@oro_product.handler.async_reindex_product_collection_handler']]
            - ['setAccumulateMessageFactory', ['@oro_product.model.accumulate_segment_message_factory']]
        tags:
            - { name: console.command }

    Oro\Bundle\ProductBundle\Command\ResizeAllProductImagesCommand:
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@event_dispatcher'
        tags:
            - { name: console.command }
