services:
    _defaults:
        public: true

    Oro\Bundle\ProductBundle\Controller\ProductController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_product.service.product_update_handler, key: Oro\Bundle\ProductBundle\Form\Handler\ProductUpdateHandler }
            - { name: container.service_subscriber, id: oro_product.provider.page_template_provider, key: Oro\Bundle\ProductBundle\Provider\PageTemplateProvider }
            - { name: container.service_subscriber, id: oro_ui.html_tag_helper }

    Oro\Bundle\ProductBundle\Controller\Frontend\ProductController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_product.layout.data_provider.product_view_form_availability_provider, key: Oro\Bundle\ProductBundle\Layout\DataProvider\ProductViewFormAvailabilityProvider }

    Oro\Bundle\ProductBundle\Controller\BrandController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\ProductBundle\Controller\Frontend\BrandController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\ProductBundle\Controller\AjaxGetProductsCountController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\ProductBundle\Controller\AjaxProductUnitController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_product.formatter.product_unit_label, key: Oro\Bundle\ProductBundle\Formatter\UnitLabelFormatter }

    Oro\Bundle\ProductBundle\Controller\Frontend\AjaxProductVariantController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\ProductBundle\Controller\Frontend\QuickAddController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\ProductBundle\Controller\Frontend\AjaxProductController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\ProductBundle\Controller\Frontend\AjaxProductUnitController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_product.formatter.product_unit_label, key: Oro\Bundle\ProductBundle\Formatter\UnitLabelFormatter }

    Oro\Bundle\ProductBundle\Controller\Frontend\ExportController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
