services:
    _defaults:
        public: true

    Oro\Bundle\ProductBundle\Controller\ProductController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: oro_product.service.product_update_handler, key: Oro\Bundle\ProductBundle\Form\Handler\ProductUpdateHandler }
            - { name: container.service_subscriber, id: oro_product.provider.page_template_provider, key: Oro\Bundle\ProductBundle\Provider\PageTemplateProvider }
            - { name: container.service_subscriber, id: oro_ui.html_tag_helper }

    Oro\Bundle\ProductBundle\Controller\Frontend\ProductController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: 'oro_product.layout.data_provider.product_view_form_availability_provider' }

    Oro\Bundle\ProductBundle\Controller\BrandController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\ProductBundle\Controller\Frontend\ExportController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\ProductBundle\Controller\Frontend\QuickAddController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
