Oro\Bundle\ProductBundle\Entity\Product:
    properties:
        type:
            - EqualTo:
                value: kit
                message: 'oro.shoppinglist.product_kit_is_available_for_purchase.product.type.kit.message'
                groups: [product_kit_is_available_for_purchase]
            - EqualTo:
                value: simple
                groups:
                    - product_kit_item_product_is_available_for_purchase
                    - product_kit_item_line_item
        status:
            - EqualTo:
                value: enabled
                message: 'oro.shoppinglist.product_kit_is_available_for_purchase.product.status.enabled.message'
                groups:
                    - product_kit_is_available_for_purchase
                    - product_kit_item_product_is_available_for_purchase
        kitItems:
            - Oro\Bundle\ShoppingListBundle\Validator\Constraints\ProductKitItemCollectionIsAvailableForPurchase:
                groups: [product_kit_is_available_for_purchase]

Oro\Bundle\ProductBundle\Entity\ProductKitItem:
    properties:
        kitItemProducts:
            - Oro\Bundle\ShoppingListBundle\Validator\Constraints\ProductKitItemProductCollectionIsAvailableForPurchase:
                groups: [product_kit_item_is_available_for_purchase]

Oro\Bundle\ProductBundle\Entity\ProductKitItemProduct:
    properties:
        product:
            - Valid:
                  groups: [product_kit_item_product_is_available_for_purchase]

Oro\Bundle\ShoppingListBundle\Entity\LineItem:
    constraints:
        - Oro\Bundle\ShoppingListBundle\Validator\Constraints\LineItem:
            groups: [update]
        - Oro\Bundle\ProductBundle\Validator\Constraints\QuantityUnitPrecision:
            path: quantity
            groups: [Default, create, update, add_product, add_product_kit_line_item]
        - Oro\Bundle\InventoryBundle\Validator\Constraints\QuantityToOrder:
            groups: [create, update, datagrid_line_items_data]
    properties:
        product:
            - NotBlank:
                groups: [create, update, add_product, add_product_kit_line_item, datagrid_line_items_data]
        quantity:
            - Oro\Bundle\ValidationBundle\Validator\Constraints\Decimal:
                groups: [create, update, add_product, add_product_kit_line_item, datagrid_line_items_data]
            - AtLeastOneOf:
                  constraints:
                    - Expression:
                          expression: "!this.product || this.product.isConfigurable()"
                    - Oro\Bundle\ValidationBundle\Validator\Constraints\GreaterThanZero: ~
                  message: 'oro.shoppinglist.lineitem.quantity.greater_than_zero'
                  includeInternalMessages: false
                  groups: [create, update, add_product, add_product_kit_line_item, datagrid_line_items_data]
            - NotBlank:
                groups: [create, update, add_product, add_product_kit_line_item, datagrid_line_items_data]
        unit:
            - NotBlank:
                groups: [create, update, add_product, add_product_kit_line_item, datagrid_line_items_data]
        shoppingList:
            - NotBlank:
                groups: [create, update]
        notes:
            - Length:
                max: 2048
                groups: [Default, create, update, add_product, add_product_kit_line_item]
        kitItemLineItems:
            - Expression:
                expression: "!this.product || !this.product.isKit() || value.count()"
                groups: [Default, create, update, add_product, add_product_kit_line_item]
            - Valid:
                groups: [add_product_kit_line_item]
        checksum:
            - NotNull: ~
            - Length:
                max: 40

Oro\Bundle\ShoppingListBundle\Entity\ShoppingList:
    properties:
        label:
            - NotBlank: ~
            - Length:
                max: 255
        totals:
            - Valid: ~
        notes:
            - Length:
                max: 2048
        lineItems:
            - Valid: ~

Oro\Bundle\ShoppingListBundle\Entity\ShoppingListTotal:
    properties:
        subtotalValue:
            - Type:
                type: numeric
                groups: [create, update, add_product, add_product_kit_line_item]
            - Oro\Bundle\ValidationBundle\Validator\Constraints\NumericRange:
                minMessage: 'oro.shoppinglist.subtotal.min.error.label'
                maxMessage: 'oro.shoppinglist.subtotal.max.error.label'
                groups: [Default, add_product_kit_line_item]

Oro\Bundle\ShoppingListBundle\Model\MatrixCollectionColumn:
    constraints:
        - Oro\Bundle\ShoppingListBundle\Validator\Constraints\MatrixCollectionColumn: ~
    properties:
        quantity:
            - Oro\Bundle\ValidationBundle\Validator\Constraints\Decimal: ~
            - Oro\Bundle\ValidationBundle\Validator\Constraints\GreaterThanZero: ~

Oro\Bundle\ShoppingListBundle\Entity\ProductKitItemLineItem:
    constraints:
        - Oro\Bundle\ProductBundle\Validator\Constraints\QuantityUnitPrecision:
            path: quantity
            groups: [Default, create, update, add_product_kit_line_item]
    properties:
        lineItem:
            - NotNull:
                groups: [Default, create, update, add_product_kit_line_item]
        kitItem:
            - NotNull:
                groups: [Default, create, update, add_product_kit_line_item]
        product:
            - NotNull:
                groups: [Default, create, update, add_product_kit_line_item]
            - Expression:
                expression: 'this.kitItem && this.kitItem.getProducts().contains(value)'
                groups: [Default, create, update, add_product_kit_line_item]
            - AtLeastOneOf:
                constraints:
                    - Expression:
                        expression: 'value && value.isEnabled()'
                    - Expression:
                        expression: 'this.kitItem && this.kitItem.optional'
                message: 'oro.shoppinglist.product_kit_item_line_item.product.status_required.message'
                includeInternalMessages: false
                groups: [Default, create, update, add_product_kit_line_item]
            - AtLeastOneOf:
                constraints:
                    - Expression:
                        expression: 'value && value.isEnabled()'
                    - Expression:
                        expression: 'this.kitItem && !this.kitItem.optional'
                message: 'oro.shoppinglist.product_kit_item_line_item.product.status_optional.message'
                includeInternalMessages: false
                groups: [Default, create, update, add_product_kit_line_item]
            - Oro\Bundle\PlatformBundle\Validator\Constraints\ValidEmbeddable:
                embeddedGroups: [product_kit_item_line_item]
        quantity:
            - Expression:
                expression: 'value && this.product'
                message: 'oro.shoppinglist.product_kit_item_line_item.quantity.not_blank.message'
                groups: [Default, create, update, add_product_kit_line_item]
            - Type:
                type: float
                groups: [Default, create, update, add_product_kit_line_item]
            - Oro\Bundle\ValidationBundle\Validator\Constraints\GreaterThanZero:
                groups: [Default, create, update, add_product_kit_line_item]
            - Sequentially:
                constraints:
                    - Expression:
                        expression: 'this.kitItem or !value'
                        message: 'oro.shoppinglist.product_kit_item_line_item.quantity.kit_item.not_blank.message'
                    - Range:
                        minPropertyPath: 'kitItem.minimumQuantity'
                        maxPropertyPath: 'kitItem.maximumQuantity'
                groups: [Default, create, update, add_product_kit_line_item]
        unit:
            - NotNull:
                groups: [Default, create, update, add_product_kit_line_item]
            - Sequentially:
                constraints:
                    - Expression:
                        expression: 'this.kitItem or !value'
                        message: 'oro.shoppinglist.product_kit_item_line_item.unit.kit_item.not_blank.message'
                    - EqualTo:
                        propertyPath: kitItem.productUnit
                groups: [Default, create, update, add_product_kit_line_item]
        sortOrder:
            - Type:
                type: integer
                groups: [Default, create, update, add_product_kit_line_item]
            - Range:
                # Minimum of 4-byte integer value.
                min: -2147483648
                # Maximum of 4-byte integer value.
                max: 2147483647
                groups: [Default, create, update, add_product_kit_line_item]

Oro\Bundle\ShoppingListBundle\Model\ShoppingListLineItemsHolder:
    properties:
        lineItems:
            - Valid: ~
