entity_config:
    attribute:
        # You can find out more about attributes in the documentation: https://doc.oroinc.com/backend/configuration/annotation/config-field.html#attribute
        field:
            items:
                searchable:
                    form:
                        options:
                            tooltip: oro.product.entity_config.field.items.attribute.searchable.tooltip
                filterable:
                    form:
                        options:
                            tooltip: oro.product.entity_config.field.items.attribute.filterable.tooltip
                sortable:
                    form:
                        options:
                            tooltip: oro.product.entity_config.field.items.attribute.sortable.tooltip
                use_in_export:
                    form:
                        options:
                            tooltip: oro.product.entity_config.field.items.attribute.use_in_export.tooltip
