Oro\Bundle\ProductBundle\Entity\Product:
    alias: oro_product_WEBSITE_ID
    fields:
        -
            name: product_id
            type: integer
        -
            name: sku_uppercase
            type: text
        -
            name: status
            type: text
            fulltext: false
        -
            name: type
            type: text
            fulltext: false
        -
            name: is_variant
            type: integer
        -
            name:  all_text
            type:  text
            store: false
            default_search_field: true
        -
            name:  all_text_LOCALIZATION_ID
            type:  text
            store: false
        -
            name: assigned_to_ASSIGN_TYPE_ASSIGN_ID
            type: integer
        -
            name: image_product_large
            type: text
            fulltext: false
            group: image
        -
            name: image_product_medium
            type: text
            fulltext: false
            group: image
        -
            name: image_product_small
            type: text
            fulltext: false
            group: image
        -
            name: product_units
            type: text
            fulltext: false
        -
            name: primary_unit
            type: text
            fulltext: false
        -
            name: attribute_family_id
            type: integer
        -
            name: manually_added_to_ASSIGN_TYPE_ASSIGN_ID
            type: integer

Oro\Bundle\ProductBundle\Entity\Brand:
    alias: oro_brand_WEBSITE_ID
    fields:
        -
            name: name_LOCALIZATION_ID
            type: text
        -
            name: short_description_LOCALIZATION_ID
            type: text
