styles:
    inputs:
        - 'bundles/oropricing/blank/scss/variables/product-price-filter-config.scss'
        - 'bundles/oropricing/blank/scss/variables/product-price-config.scss'
        - 'bundles/oropricing/blank/scss/variables/product-prices-config.scss'
        - 'bundles/oropricing/blank/scss/variables/product-totals-config.scss'
        - 'bundles/oropricing/blank/scss/variables/product-price-hint-config.scss'
        - 'bundles/oropricing/blank/scss/variables/product-price-hint-btn-config.scss'

        - 'bundles/oropricing/blank/scss/components/product-price-hint.scss'
        - 'bundles/oropricing/blank/scss/components/product-price-hint-btn.scss'

        - 'bundles/oropricing/blank/scss/styles.scss'
