styles:
    inputs:
        - 'bundles/oroproduct/blank/scss/variables/product-view-attributes-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/product-view-attribute-box-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/product-view-layout-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/product-view-desc-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/product-view-desc-list-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/product-view-desc-title-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/product-view-quantity-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/product-action-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/product-view-media/container-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/product-view-media/gallery-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/product-view-media/slider-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/product-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/product-item-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/sku-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/product-sticker-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/view-product-gallery-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/product-list-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/embedded-products-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/product-popup-header.scss'
        - 'bundles/oroproduct/blank/scss/variables/product-filters-root-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/search-autocomplete-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/elevatezoom-config.scss'
        - 'bundles/oroproduct/blank/scss/variables/toggle-sidebar-btn-config.scss'

        - 'bundles/oroproduct/blank/scss/components/product.scss'
        - 'bundles/oroproduct/blank/scss/components/product-item.scss'
        - 'bundles/oroproduct/blank/scss/components/product-list.scss'
        - 'bundles/oroproduct/blank/scss/components/product-filters-root.scss'
        - 'bundles/oroproduct/blank/scss/components/toggle-sidebar-btn.scss'
        - 'bundles/oroproduct/blank/scss/styles.scss'
