entity_config:
    slug:
        # You can find out more about attributes in the documentation: https://doc.oroinc.com/backend/configuration/annotation/config.html#slug
        entity:
            items:
                source:
                    options:
                        default_value: null
                        indexed: true
