services:
    _defaults:
        public: false

    Oro\Bundle\CMSBundle\Command\SanitizeWysiwygStyleFieldsCommand:
        arguments:
            - '@doctrine'
            - !tagged_iterator 'oro_security.fields_sanitizer'
            - '@oro_entity_config.config_manager'
            - '@oro_config.manager'
            - '@translator'
            - '@oro_entity_config.provider.entity_url_generator'
        tags:
            - { name: console.command }
