services:
    oro_pricing.tests.database_triggers.manager.combined_prices:
        decorates: oro_pricing.database_triggers.manager.combined_prices
        parent: oro_pricing.database_triggers.manager.combined_prices
        public: true

    oro_pricing.tests.combined_price_list_schedule_command:
        alias: Oro\Bundle\PricingBundle\Command\CombinedPriceListScheduleCommand
        public: true

    oro_pricing.tests.api.skipped_entity_provider:
        class: Oro\Bundle\ApiBundle\Tests\Functional\Environment\SkippedEntityProvider
        decorates: oro_api.tests.skipped_entity_provider
        arguments:
            - '@oro_pricing.tests.api.skipped_entity_provider.inner'
        calls:
            - [addSkippedEntity, ['Oro\Bundle\PricingBundle\Entity\ProductPrice']]
            - [addSkippedEntity, ['Oro\Bundle\PricingBundle\Entity\PriceListSchedule', ['create']]]

    oro_pricing.tests.cache.rule_cache.storage:
        decorates: oro_pricing.cache.rule_cache.storage
        parent: oro_pricing.cache.rule_cache.storage
        public: true
