oro_shipping_methods_configs_rule:
    resource:     "@OroShippingBundle/Controller/ShippingMethodsConfigsRuleController.php"
    type:         annotation
    prefix:       /shippingrule

oro_shipping_product_shipping_options_ajax:
    resource:     "@OroShippingBundle/Controller/AjaxProductShippingOptionsController.php"
    type:         annotation
    prefix:       /shipping/product-shipping

oro_shipping_multishipping:
    resource:     "@OroShippingBundle/Controller/MultiShippingController.php"
    type:         annotation
    prefix:       /multishipping


#
# DEPRECATED OLD REST API ROUTES
#

oro_api_coptions_shippingrules:
    path: '/api/rest/{version}/shippingrules.{_format}'
    methods: [OPTIONS]
    defaults:
        _controller: 'Oro\Bundle\ShippingBundle\Controller\Api\Rest\ShippingMethodsConfigsRuleController::optionsAction'
        _format: json
        version: latest
    requirements:
        _format: json
        version: latest|v1

oro_api_options_shippingrules:
    path: '/api/rest/{version}/shippingrules.{_format}'
    methods: [OPTIONS]
    defaults:
        _controller: 'Oro\Bundle\ShippingBundle\Controller\Api\Rest\ShippingMethodsConfigsRuleController::optionsAction'
        _format: json
        version: latest
    requirements:
        _format: json
        version: latest|v1


#
# OLD REST API ROUTES
#

oro_api_enable_shippingrules:
    path: '/api/rest/{version}/shippingrules/{id}/enable.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\ShippingBundle\Controller\Api\Rest\ShippingMethodsConfigsRuleController::enableAction'
        version: latest
        _format: json
    requirements:
        version: latest|v1
        id: \d+
        _format: json

oro_api_disable_shippingrules:
    path: '/api/rest/{version}/shippingrules/{id}/disable.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\ShippingBundle\Controller\Api\Rest\ShippingMethodsConfigsRuleController::disableAction'
        version: latest
        _format: json
    requirements:
        version: latest|v1
        id: \d+
        _format: json
